import { test } from "node:test";
import assert from "node:assert/strict";
import { inflateSync } from "node:zlib";

export async function runTests(image,server){
 const {toPoint,rectFrom,selectionBounds,editLayout,blendPixels,encodePNG}=image;
 const {handleAI,pngInfo,readLimited}=server;
 const png=async(w,h,fill=[100,80,200,255])=>{const bytes=new Uint8ClampedArray(w*h*4);for(let i=0;i<bytes.length;i+=4)bytes.set(fill,i);return new Uint8Array(await (await encodePNG(bytes,w,h)).arrayBuffer());};
 const source=await png(30,20),padded=await png(1536,1024),mask=await png(1536,1024,[0,0,0,0]);
 const form=(mode="ask",selected=false)=>{const f=new FormData();f.set("prompt","What is this part?");f.set("image",new Blob([mode==="ask"?source:padded],{type:"image/png"}),"image.png");const s={kind:selected?(mode==="ask"?"rectangle":"selected"):"whole",bounds:selected?{x:3,y:2,width:6,height:8}:null,width:30,height:20};if(mode==="edit"){s.layout=editLayout(30,20);f.set("mask",new Blob([mask],{type:"image/png"}),"mask.png");}else if(selected){for(const k of ["context","crop"])f.set(k,new Blob([source],{type:"image/png"}),`${k}.png`);}f.set("selection",JSON.stringify(s));return f;};
 const request=(f,origin="http://localhost:5173")=>new Request("http://localhost:5173/api/ask",{method:"POST",headers:{Origin:origin},body:f});
 const responseJSON=r=>r.json();
 await test("coordinates stay correct at zoom, scroll offsets and CSS scales",()=>{assert.deepEqual(toPoint(250,200,{left:100,top:100,width:300,height:200},1500,1000),{x:750,y:500});assert.deepEqual(toPoint(-20,500,{left:100,top:100,width:300,height:200},1500,1000),{x:0,y:1000});});
 await test("reverse rectangles and brush bounds are clamped in image space",()=>{assert.deepEqual(rectFrom({x:100.2,y:70.2},{x:20.4,y:10.6}),{x:20,y:10,width:81,height:61});assert.deepEqual(selectionBounds(100,80,[{kind:"brush",radius:12,points:[{x:2,y:3},{x:99,y:79}]}]),{x:0,y:0,width:100,height:80});assert.equal(selectionBounds(100,80,[]),null);});
 await test("edit padding preserves source aspect ratio and stable offsets",()=>{const l=editLayout(1200,400);assert.deepEqual(l,{width:1536,height:1024,x:0,y:256,drawWidth:1536,drawHeight:512});assert.equal(editLayout(400,1200).height,1536);assert.equal(editLayout(500,500).width,1024);});
 await test("compositing keeps every unselected RGBA byte unchanged",()=>{const src=new Uint8ClampedArray([17,42,91,1,10,40,70,127,4,5,6,255]),edit=new Uint8ClampedArray([255,0,0,255,200,220,240,255,80,90,100,255]),coverage=new Uint8ClampedArray([0,0,0,0,0,0,0,128,0,0,0,255]);const result=blendPixels(src,edit,coverage);assert.deepEqual([...result.slice(0,4)],[17,42,91,1]);assert.deepEqual([...result.slice(8)],[80,90,100,255]);assert.ok(result[7]>127&&result[7]<255);assert.deepEqual([...src.slice(0,4)],[17,42,91,1]);});
 await test("PNG export preserves low alpha raw RGBA without canvas rounding",async()=>{const raw=new Uint8ClampedArray([17,42,91,1,10,40,70,127,4,5,6,255]),encoded=new Uint8Array(await (await encodePNG(raw,3,1)).arrayBuffer());assert.deepEqual(pngInfo(encoded),{width:3,height:1});let offset=8;const chunks=[];const view=new DataView(encoded.buffer);while(offset<encoded.length){const length=view.getUint32(offset);if(Buffer.from(encoded.slice(offset+4,offset+8)).toString()==="IDAT")chunks.push(encoded.slice(offset+8,offset+8+length));offset+=12+length;}assert.deepEqual([...inflateSync(Buffer.concat(chunks)).slice(1)],[...raw]);});
 await test("stream cap enforces actual bytes even without content length",async()=>{const body=new ReadableStream({start(c){c.enqueue(new Uint8Array(10));c.enqueue(new Uint8Array(10));c.close();}});await assert.rejects(()=>readLimited(body,15),e=>e.status===413);});
 await test("PNG validation rejects truncated files and huge forged dimensions",()=>{assert.throws(()=>pngInfo(source.slice(0,-5)));const huge=new Uint8Array(source);new DataView(huge.buffer).setUint32(16,100000);assert.throws(()=>pngInfo(huge),e=>e.status===413);});
 await test("missing key returns useful 503 without making an upstream call",async()=>{let called=false;const r=await handleAI(request(form()),"ask",{},async()=>{called=true;throw Error();});assert.equal(r.status,503);assert.equal((await responseJSON(r)).code,"AI_NOT_CONFIGURED");assert.equal(called,false);});
 await test("cross-origin requests and duplicate fields are rejected",async()=>{assert.equal((await handleAI(request(form(),"https://bad.example"),"ask",{})).status,403);const f=form();f.append("prompt","duplicate");assert.equal((await handleAI(request(f),"ask",{})).status,400);});
 await test("Ask sends original, annotated selection and crop to real API contract",async()=>{let payload;const r=await handleAI(request(form("ask",true)),"ask",{key:"test-only"},async(url,options)=>{assert.equal(url,"https://api.openai.com/v1/responses");payload=JSON.parse(options.body);return Response.json({status:"completed",output:[{type:"message",content:[{type:"output_text",text:"A test fixture answer."}]}]});});assert.equal(r.status,200);assert.equal((await responseJSON(r)).answer,"A test fixture answer.");assert.equal(payload.store,false);assert.equal(payload.input.at(-1).content.filter(c=>c.type==="input_image").length,3);assert.ok(payload.input.at(-1).content[0].text.includes('"x":3'));});
 await test("Edit sends PNG alpha mask and supported model params, returns PNG",async()=>{const r=await handleAI(request(form("edit",true)),"edit",{key:"test-only"},async(url,options)=>{assert.equal(url,"https://api.openai.com/v1/images/edits");assert.equal(options.body.get("model"),"gpt-image-2");assert.equal(options.body.get("size"),"1536x1024");assert.equal(options.body.has("input_fidelity"),false);assert.equal(options.body.get("mask").type,"image/png");return Response.json({data:[{b64_json:Buffer.from(padded).toString("base64")}]});});assert.equal(r.status,200);assert.equal(r.headers.get("content-type"),"image/png");assert.deepEqual(new Uint8Array(await r.arrayBuffer()),padded);});
 await test("provider errors are sanitized and refusal is actionable",async()=>{for(const [status,expected] of [[401,502],[403,502],[429,429],[500,502],[400,422]]){const r=await handleAI(request(form()),"ask",{key:"test-only"},async()=>Response.json({error:"secret key and internal details"},{status}));assert.equal(r.status,expected);assert.ok(!(await r.text()).includes("secret key"));}const r=await handleAI(request(form()),"ask",{key:"test-only"},async()=>Response.json({output:[{content:[{type:"refusal",refusal:"no"}]}]}));assert.equal((await r.json()).code,"REFUSAL");});
 await test("invalid model image or output dimensions leave edit unsuccessful",async()=>{const r=await handleAI(request(form("edit")),"edit",{key:"test-only"},async()=>Response.json({data:[{b64_json:Buffer.from(source).toString("base64")}]}));assert.equal(r.status,502);});
}
