"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Aperture, Upload, ImagePlus, MessageCircle, Sparkles, ArrowUp, Scan, SquareDashed, Brush, Undo2, ZoomIn, ZoomOut, Download, Columns2, X, LoaderCircle, Info, Check, Expand, ChevronRight, History } from "lucide-react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Slider } from "@/components/ui/slider";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Toaster, toast } from "sonner";
import { normalize, toPoint, rectFrom, selectionMask, selectionBounds, selectionPreview, askFiles, editFiles, finishEdit, type Picture, type Shape } from "@/lib/image-workspace";

type Mode="ask"|"edit";
type Version={id:number;picture:Picture};
type Entry={id:string;mode:Mode;prompt:string;sourceVersion:number;selection:string;selectionKey:string;bounds:string;thumbnail:string;status:"pending"|"done"|"error"|"cancelled";answer?:string;error?:string;resultVersion?:number;undone?:boolean};
type Inspect={thumbnail:string;selection:string;bounds:string;sourceVersion:number};
type Status={configured:boolean;askModel:string;editModel:string};
const errorMessage=(error:unknown)=>error instanceof Error?error.message:"Something went wrong. Please try again.";

export default function Workspace(){
  const input=useRef<HTMLInputElement>(null),stage=useRef<HTMLDivElement>(null),overlay=useRef<HTMLCanvasElement>(null),textInput=useRef<HTMLTextAreaElement>(null),historyEnd=useRef<HTMLDivElement>(null);
  const [versions,setVersions]=useState<Version[]>([]),[shapes,setShapes]=useState<Shape[]>([]),[selectionUndo,setSelectionUndo]=useState<Shape[][]>([]),[draft,setDraft]=useState<Shape|null>(null);
  const [tool,setTool]=useState<"rect"|"brush">("rect"),[brushSize,setBrushSize]=useState(48),[zoom,setZoom]=useState(1),[size,setSize]=useState({width:800,height:500});
  const [mode,setMode]=useState<Mode>("ask"),[prompts,setPrompts]=useState({ask:"",edit:""}),[entries,setEntries]=useState<Entry[]>([]),[busy,setBusy]=useState<Mode|"upload"|null>(null),[status,setStatus]=useState<Status|null>(null);
  const [compare,setCompare]=useState(false),[split,setSplit]=useState(50),[dragOver,setDragOver]=useState(false),[inspect,setInspect]=useState<Inspect|null>(null),[help,setHelp]=useState(false),[replaceFile,setReplaceFile]=useState<File|null>(null);
  const [cursor,setCursor]=useState<{x:number;y:number}|null>(null),[elapsed,setElapsed]=useState(0);
  const urls=useRef(new Set<string>()),controller=useRef<AbortController|null>(null),nextVersion=useRef(1),selectionNumber=useRef(0),draftRef=useRef<Shape|null>(null),busyRef=useRef(false);
  const activePointer=useRef<number|null>(null);
  const current=versions.at(-1),picture=current?.picture,previous=versions.at(-2),filtered=entries.filter(e=>e.mode===mode);
  const bounds=picture?selectionBounds(picture.width,picture.height,shapes):null;
  const fit=picture?Math.min((size.width-64)/picture.width,(size.height-70)/picture.height,1):1;
  const scale=Math.max(.02,fit)*zoom;
  const locked=!!busy;

  useEffect(()=>{let active=true;fetch("/api/status").then(r=>r.ok?r.json() as Promise<Status>:Promise.reject()).then(s=>{if(active)setStatus(s);}).catch(()=>{if(active)setStatus(null);});return()=>{active=false;};},[]);
  useEffect(()=>{const el=stage.current;if(!el)return;const r=new ResizeObserver(([entry])=>setSize({width:entry.contentRect.width,height:entry.contentRect.height}));r.observe(el);return()=>r.disconnect();},[]);
  useEffect(()=>()=>{controller.current?.abort();urls.current.forEach(url=>URL.revokeObjectURL(url));},[]);
  useEffect(()=>{if(!busy){setElapsed(0);return;}const start=Date.now(),timer=setInterval(()=>setElapsed(Math.floor((Date.now()-start)/1000)),1000);return()=>clearInterval(timer);},[busy]);
  useEffect(()=>{historyEnd.current?.scrollIntoView({block:"nearest",behavior:"smooth"});},[entries,mode]);

  const remember=(url:string)=>{urls.current.add(url);};
  const resetSelection=useCallback(()=>{setSelectionUndo(list=>[...list.slice(-29),shapes]);setShapes([]);setDraft(null);draftRef.current=null;setCompare(false);},[shapes]);
  const undoSelection=useCallback(()=>{if(!selectionUndo.length||locked)return;setShapes(selectionUndo.at(-1)!);setSelectionUndo(list=>list.slice(0,-1));},[selectionUndo,locked]);
  const undoEdit=useCallback(()=>{if(versions.length<2||locked)return;const removed=versions.at(-1)!;setVersions(list=>list.slice(0,-1));setEntries(list=>list.map(e=>e.resultVersion===removed.id?{...e,undone:true}:e));setShapes([]);setSelectionUndo([]);setCompare(false);toast("Edit undone. Previous image restored.");},[versions,locked]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches("input,textarea,[contenteditable=true]"))return;if((e.ctrlKey||e.metaKey)&&e.key==="z"){e.preventDefault();selectionUndo.length?undoSelection():undoEdit();}if(e.key==="Escape"){setDraft(null);draftRef.current=null;setCompare(false);}if(!locked&&e.key.toLowerCase()==="b")setTool("brush");if(!locked&&e.key.toLowerCase()==="r")setTool("rect");};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);},[selectionUndo,undoSelection,undoEdit,locked]);

  useEffect(()=>{
    const c=overlay.current;if(!c||!picture)return;c.width=picture.width;c.height=picture.height;const ctx=c.getContext("2d")!;
    const all=draft?(draft.kind==="rect"?[draft]:[...shapes,draft]):shapes;
    const mask=selectionMask(c.width,c.height,all);ctx.drawImage(mask,0,0);ctx.globalCompositeOperation="source-in";ctx.fillStyle="rgba(164,133,255,.34)";ctx.fillRect(0,0,c.width,c.height);ctx.globalCompositeOperation="source-over";
    for(const s of all)if(s.kind==="rect"){const r=rectFrom(s.a,s.b);ctx.strokeStyle="#d1bdff";ctx.lineWidth=1.5/scale;ctx.setLineDash([6/scale,4/scale]);ctx.strokeRect(r.x,r.y,r.width,r.height);ctx.setLineDash([]);for(const [x,y] of [[r.x,r.y],[r.x+r.width,r.y],[r.x,r.y+r.height],[r.x+r.width,r.y+r.height]]){ctx.fillStyle="#e2d7ff";ctx.fillRect(x-3/scale,y-3/scale,6/scale,6/scale);}}
  },[picture,shapes,draft,scale]);

  async function loadFile(file:File){
    if(busyRef.current)return;busyRef.current=true;setBusy("upload");
    try{const p=await normalize(file);remember(p.url);urls.current.forEach(url=>{if(url!==p.url){URL.revokeObjectURL(url);urls.current.delete(url);}});setVersions([{id:0,picture:p}]);setEntries([]);setShapes([]);setSelectionUndo([]);setDraft(null);setPrompts({ask:"",edit:""});setZoom(1);setCompare(false);nextVersion.current=1;selectionNumber.current=0;toast.success("Image ready. Select a detail or use the whole image.");}
    catch(error){toast.error(errorMessage(error));}finally{setBusy(null);busyRef.current=false;if(input.current)input.current.value="";}
  }
  function chooseFile(file:File|undefined){if(!file||locked)return;if(picture&&(entries.length||versions.length>1)){setReplaceFile(file);}else void loadFile(file);}
  function pointer(e:React.PointerEvent<HTMLCanvasElement>){return toPoint(e.clientX,e.clientY,e.currentTarget.getBoundingClientRect(),picture!.width,picture!.height);}
  function begin(e:React.PointerEvent<HTMLCanvasElement>){if(!picture||locked||compare||e.button!==0||draftRef.current)return;e.preventDefault();activePointer.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);const p=pointer(e);const next:Shape=tool==="rect"?{kind:"rect",a:p,b:p}:{kind:"brush",points:[p],radius:brushSize/2};draftRef.current=next;setDraft(next);}
  function move(e:React.PointerEvent<HTMLCanvasElement>){if(!picture||activePointer.current!==null&&e.pointerId!==activePointer.current)return;const p=pointer(e);setCursor(p);const shape=draftRef.current;if(!shape)return;const next:Shape=shape.kind==="rect"?{...shape,b:p}:{...shape,points:[...shape.points,p]};draftRef.current=next;setDraft(next);}
  function end(e:React.PointerEvent<HTMLCanvasElement>){const shape=draftRef.current;if(!shape||activePointer.current!==e.pointerId)return;activePointer.current=null;draftRef.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(shape.kind==="brush"||rectFrom(shape.a,shape.b).width>=2&&rectFrom(shape.a,shape.b).height>=2){setSelectionUndo(list=>[...list.slice(-29),shapes]);setShapes(shape.kind==="rect"?[shape]:[...shapes,shape]);}setDraft(null);}
  const cancelStroke=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(activePointer.current!==e.pointerId)return;activePointer.current=null;draftRef.current=null;setDraft(null);};
  function download(){if(!picture)return;const a=document.createElement("a");a.href=picture.url;a.download=`${picture.name.replace(/\.[^.]+$/,"")}${current!.id?`-edit-${current!.id}`:"-original"}.png`;a.click();}
  function updateEntry(id:string,patch:Partial<Entry>){setEntries(list=>list.map(e=>e.id===id?{...e,...patch}:e));}
  async function submit(){
    if(!picture||!current||busyRef.current||!prompts[mode].trim())return;
    if(mode==="edit"&&versions.length>=11){toast.error("This session has 10 edits. Download the result and upload it to begin a new session.");return;}
    busyRef.current=true;const requestMode=mode,source=picture,sourceVersion=current.id,selection=structuredClone(shapes),prompt=prompts[mode].trim(),id=crypto.randomUUID();
    const b=selectionBounds(source.width,source.height,selection),label=b?`Area ${String(++selectionNumber.current).padStart(2,"0")}`:"Whole image";
    const abort=new AbortController();controller.current=abort;setBusy(requestMode);setCompare(false);
    let added=false;
    try{
      const thumbnail=await selectionPreview(source,selection,600);
      if(abort.signal.aborted)throw new DOMException("Cancelled","AbortError");
      const selectionKey=JSON.stringify(selection);
      setEntries(list=>[...list,{id,mode:requestMode,prompt,sourceVersion,selection:label,selectionKey,bounds:b?`${b.width} × ${b.height} px at ${b.x}, ${b.y}`:`${source.width} × ${source.height} px`,thumbnail,status:"pending"}]);added=true;
      let data:FormData,layout:Awaited<ReturnType<typeof editFiles>>["layout"]|undefined;
      if(requestMode==="ask"){
        data=await askFiles(source,selection);
        // Only carry context from the same image version and exact selection.
        const context=entries.filter(e=>e.mode==="ask"&&e.status==="done"&&e.sourceVersion===sourceVersion&&e.selectionKey===selectionKey).slice(-3).map(e=>({question:e.prompt.slice(0,2500),answer:(e.answer||"").slice(0,4500)}));data.set("history",JSON.stringify(context));
      }else {const prepared=await editFiles(source,selection);data=prepared.data;layout=prepared.layout;}
      data.set("prompt",prompt);
      const response=await fetch(`/api/${requestMode}`,{method:"POST",body:data,signal:abort.signal});
      if(!response.ok){const failure=await response.json().catch(()=>({error:"The server could not finish this request."})) as {error?:string};throw Error(failure.error||"The request failed. Please try again.");}
      if(requestMode==="ask"){const result=await response.json() as {answer:string;incomplete?:boolean};if(abort.signal.aborted)throw new DOMException("Cancelled","AbortError");updateEntry(id,{status:"done",answer:result.answer+(result.incomplete?"\n\nThis answer reached its length limit. Ask a follow-up for more detail.":"")});}
      else {const result=await finishEdit(source,selection,await response.blob(),layout!);if(abort.signal.aborted){URL.revokeObjectURL(result.url);throw new DOMException("Cancelled","AbortError");}remember(result.url);const version=nextVersion.current++;setVersions(list=>[...list,{id:version,picture:result}]);updateEntry(id,{status:"done",resultVersion:version});setShapes([]);setSelectionUndo([]);setCompare(true);setSplit(50);toast.success("Edit ready. Compare it with the previous version.");}
      setPrompts(p=>({...p,[requestMode]:""}));
    }catch(error){const cancelled=abort.signal.aborted;if(added)updateEntry(id,{status:cancelled?"cancelled":"error",error:cancelled?"Cancelled. Your image is unchanged. The provider may still charge for a submitted request.":errorMessage(error)});else toast.error(errorMessage(error));}
    finally{setBusy(null);busyRef.current=false;controller.current=null;}
  }

  // Optional browser agent access shares the visible selection action and state.
  const webState=useRef({picture,shapes,locked,resetSelection});webState.current={picture,shapes,locked,resetSelection};
  useEffect(()=>{
    type ToolContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
    const mc=(document as Document&{modelContext?:ToolContext}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();
    for(const tool of [
      {name:"get_image_workspace",description:"Read the current image dimensions and selected region. Does not send images to AI.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const s=webState.current;return {loaded:!!s.picture,width:s.picture?.width,height:s.picture?.height,selection:s.picture?selectionBounds(s.picture.width,s.picture.height,s.shapes):null,busy:s.locked};}},
      {name:"use_whole_image",description:"Clear the current selection so the next question or edit targets the whole image. Does not submit a request.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw Error("Expected an empty object.");const s=webState.current;if(!s.picture||s.locked)throw Error("Load an image and wait for the current request to finish.");s.resetSelection();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {selection:"whole"};}}
    ])try{void Promise.resolve(mc.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  },[]);

  return <main className="app-shell">
    <Toaster position="bottom-center" richColors closeButton/>
    <header className="app-header"><a className="brand" href="/" onClick={e=>e.preventDefault()} aria-label="Aperture image workspace"><span className="brand-icon"><Aperture size={23}/></span>Aperture<span className="brand-caption">IMAGE WORKSPACE</span></a><div className="header-actions"><button className="help-button" aria-label="Help and setup" title="Help and setup" onClick={()=>setHelp(true)}><Info size={19}/></button><button className="button" disabled={locked} onClick={()=>input.current?.click()}><Upload size={16}/><span>{picture?"New image":"Upload image"}</span></button><button className="button download-button" disabled={!picture||locked} onClick={download}><Download size={16}/><span>Download</span></button></div></header>
    <input data-testid="image-upload" aria-label="Upload image" ref={input} className="sr-only" tabIndex={-1} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseFile(e.target.files?.[0])}/>
    <div className="workspace"><section className="viewer" aria-label="Image workspace" onDragOver={e=>{e.preventDefault();if(!locked)setDragOver(true);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragOver(false);}} onDrop={e=>{e.preventDefault();setDragOver(false);chooseFile(e.dataTransfer.files[0]);}}>
      <div className="viewer-heading"><div className="file-heading">{picture?<><span className="file-name">{picture.name}</span><span className="version-pill">{current!.id?`Version ${current!.id}`:"Original"}</span></>:<span>YOUR CANVAS</span>}</div><span className="workspace-index">01 / WORKSPACE</span></div>
      <div className="viewer-tools" aria-label="Image tools"><div className="tool-group"><button className={tool==="rect"?"selected":""} aria-label="Rectangle selection" aria-pressed={tool==="rect"} title="Rectangle selection (R)" disabled={!picture||locked} onClick={()=>{setTool("rect");setCompare(false);}}><SquareDashed size={18}/></button><button className={tool==="brush"?"selected":""} aria-label="Brush selection" aria-pressed={tool==="brush"} title="Brush selection (B)" disabled={!picture||locked} onClick={()=>{setTool("brush");setCompare(false);}}><Brush size={18}/></button></div><span className="tool-divider"/><button className="whole-button" disabled={!picture||locked} onClick={resetSelection}><Scan size={16}/>Use whole image</button><button className="clear-button" title="Clear selection" aria-label="Clear selection" disabled={!shapes.length||locked} onClick={resetSelection}><X size={16}/><span>Clear</span></button><button title="Undo selection (Ctrl/Cmd Z)" aria-label="Undo selection" disabled={!selectionUndo.length||locked} onClick={undoSelection}><Undo2 size={17}/></button><div className="tool-spacer"/>{tool==="brush"&&picture&&<div className="brush-control"><span>{brushSize} px</span><Slider aria-label="Brush diameter" min={4} max={180} step={2} value={[brushSize]} disabled={locked} onValueChange={v=>setBrushSize(v[0])}/></div>}</div>
      <div className={`canvas-stage ${dragOver?"drag-over":""}`} ref={stage}>
        {picture?<div className="image-scroll"><div className="image-frame" style={{width:picture.width*scale,height:picture.height*scale}}>
          <img draggable={false} src={picture.url} width={picture.width} height={picture.height} alt={`Current image: ${picture.name}`} className="working-image"/>
          {compare&&previous&&<><img draggable={false} src={previous.picture.url} alt="Before the latest edit" className="before-image" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}/><div className="compare-line" style={{left:`${split}%`}}><Columns2 size={18}/></div><span className="compare-label before">Before</span><span className="compare-label after">After</span></>}
          <canvas ref={overlay} data-testid="selection-canvas" className={`selection-canvas ${tool==="brush"?"brush-canvas":""}`} style={{visibility:compare?"hidden":"visible",pointerEvents:locked||compare?"none":"auto"}} aria-label="Drag to select an area. Use whole image to select without drawing." onPointerDown={begin} onPointerMove={move} onPointerUp={end} onPointerCancel={cancelStroke} onLostPointerCapture={cancelStroke} onPointerLeave={()=>setCursor(null)}/>
          {cursor&&tool==="brush"&&!compare&&!locked&&<div className="brush-cursor" style={{left:cursor.x*scale,top:cursor.y*scale,width:brushSize*scale,height:brushSize*scale}}/>}
        </div></div>:<div className="upload-empty"><div className="upload-icon"><ImagePlus size={32}/></div><h1>A little more possibility<br/>in every image.</h1><p>Drop an image here to take a closer look.<br/>Ask about a detail. Change what you see.</p><button className="button primary" disabled={locked} onClick={()=>input.current?.click()}>{busy==="upload"?<LoaderCircle size={17} className="spin"/>:<Upload size={17}/>} Choose an image</button><small>JPG, PNG or WebP · up to 20 MB</small></div>}
        {dragOver&&<div className="drop-overlay"><Upload size={36}/><span>Drop to open your image</span></div>}
      </div>
      {picture&&<><div className="canvas-context"><span><span className={`selection-dot ${bounds?"has-selection":""}`}/>{compare?"Drag the slider to compare":bounds?`${bounds.width} × ${bounds.height} px selected`:tool==="brush"?"Paint over a detail to select it":"Drag a rectangle around a detail"}</span><div className="zoom-tools"><button aria-label="Zoom out" disabled={zoom<=.5} onClick={()=>setZoom(z=>Math.max(.5,z-.25))}><ZoomOut size={16}/></button><button title="Fit image to view" onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><button aria-label="Zoom in" disabled={zoom>=4} onClick={()=>setZoom(z=>Math.min(4,z+.25))}><ZoomIn size={16}/></button><button title="Fit image" aria-label="Fit image" onClick={()=>setZoom(1)}><Expand size={15}/></button></div></div>{compare&&previous&&<div className="compare-slider"><span>Before</span><Slider aria-label="Before and after comparison" min={0} max={100} value={[split]} onValueChange={v=>setSplit(v[0])}/><span>After</span></div>}<div className="version-actions"><button className={compare?"active":""} disabled={!previous||locked} onClick={()=>setCompare(v=>!v)}><Columns2 size={16}/>{compare?"Close comparison":"Compare before / after"}</button><button disabled={!previous||locked} onClick={undoEdit}><Undo2 size={16}/> Undo edit</button></div></>}
      <footer className="viewer-footer"><span>{picture?`${picture.width} × ${picture.height} px${picture.reduced?" · resized for the workspace":""}`:"A space to explore, one image at a time."}</span><span>Session only · download to keep</span></footer>
    </section>
    <aside className="conversation" aria-label="Image conversation"><div className="panel-heading"><span>Make room for curiosity.</span><small>IMAGE ASSISTANT</small></div>
      <Tabs value={mode} onValueChange={v=>setMode(v as Mode)}><TabsList className="mode-tabs" aria-label="Assistant mode"><TabsTrigger value="ask"><MessageCircle size={17}/> Ask {entries.some(e=>e.mode==="ask")&&<span className="tab-count">{entries.filter(e=>e.mode==="ask").length}</span>}</TabsTrigger><TabsTrigger value="edit"><Sparkles size={17}/> Edit {entries.some(e=>e.mode==="edit")&&<span className="tab-count">{entries.filter(e=>e.mode==="edit").length}</span>}</TabsTrigger></TabsList></Tabs>
      <div className="history-region" aria-label={mode==="ask"?"Questions and answers":"Edit history"}>
        {!filtered.length?<div className="conversation-empty"><span className="assistant-symbol">{mode==="ask"?<Aperture size={25}/>:<Sparkles size={23}/>}</span><h2>{mode==="ask"?"See more in your image.":"A small change. A new possibility."}</h2><p>{mode==="ask"?<>Select a detail or use the whole image.<br/>Then, let your curiosity lead.</>:<>Paint or select what you want to change.<br/>Describe it. We’ll take it from there.</>}</p>{(mode==="ask"?["What is this part called?","How do I fix this?","What details should I notice?"]:["Remove this object","Change this to a deep blue","Make the lighting warmer"]).map(s=><button className="suggestion" key={s} onClick={()=>{setPrompts(p=>({...p,[mode]:s}));textInput.current?.focus();}}>{s}<ArrowUp size={15}/></button>)}</div>:<div className="history-list"><div className="history-label"><History size={13}/>{mode==="ask"?"Questions & answers":"Your edits"}<span>{filtered.length}</span></div>{filtered.map(entry=><article className="history-entry" key={entry.id}><button className="selection-reference" onClick={()=>setInspect(entry)}><img src={entry.thumbnail} alt={`${entry.selection} highlighted on version ${entry.sourceVersion}`}/><span><strong>{entry.selection}</strong><small>{entry.sourceVersion?`Version ${entry.sourceVersion}`:"Original image"} · {entry.bounds}</small></span><ChevronRight size={14}/></button><p className="user-prompt">{entry.prompt}</p><div className={`answer ${entry.status==="error"?"answer-error":""}`} aria-live="polite">{entry.status==="pending"?<div className="loading-answer"><LoaderCircle size={16} className="spin"/><span>{entry.mode==="ask"?"Taking a closer look…":"Creating your edit…"}<small>{entry.mode==="edit"?"This can take up to 3 minutes.":"Reading your image and selection."}</small></span></div>:entry.status==="done"?entry.mode==="ask"?<><span className="answer-byline"><Aperture size={14}/> Aperture</span><div className="answer-text">{entry.answer}</div></>:<div className="edit-complete"><Check size={16}/><span>{entry.undone?"Edit undone":`Edit complete · Version ${entry.resultVersion}`}<small>{entry.undone?"The previous image was restored.":entry.selection==="Whole image"?"Applied to the whole image.":"Applied inside your selection."}</small></span></div>:<><span className="answer-byline">{entry.status==="cancelled"?"Request cancelled":"Couldn’t finish this request"}</span><p>{entry.error}</p>{entry.status==="error"&&<button className="retry-link" disabled={locked} onClick={()=>{setPrompts(p=>({...p,[entry.mode]:entry.prompt}));textInput.current?.focus();}}>Use this prompt again</button>}</>}</div></article>)}<div ref={historyEnd}/></div>}
      </div>
      {status?.configured===false&&<button className="connection-note" onClick={()=>setHelp(true)}><Info size={14}/><span>Connect your API key to enable AI</span><ChevronRight size={14}/></button>}
      {mode==="edit"&&<div className="edit-note"><Scan size={14}/><span>Selected edits are clipped to your mask. Edges may need refinement; select a little extra space.</span></div>}
      <form className="composer" onSubmit={e=>{e.preventDefault();void submit();}}>
        {picture&&<div className="composer-target"><Scan size={13}/>{bounds?"Selected area":"Whole image"}<span>{current!.id?`v${current!.id}`:"Original"}</span></div>}
        <textarea ref={textInput} aria-label={mode==="ask"?"Ask about the image":"Describe your edit"} value={prompts[mode]} maxLength={4000} disabled={!picture||locked} onChange={e=>setPrompts(p=>({...p,[mode]:e.target.value}))} onKeyDown={e=>{if(e.key==="Enter"&&(e.ctrlKey||e.metaKey)){e.preventDefault();void submit();}}} placeholder={!picture?"Upload an image to start…":mode==="ask"?"What would you like to know?":"Describe what you’d like to change…"}/>
        <div className="composer-bottom"><small>{busy&&busy!=="upload"?`${busy==="ask"?"Looking closer":"Editing"} · ${elapsed}s`:mode==="ask"?"Ask about what you see":"Make it yours"}</small>{busy&&busy!=="upload"?<button type="button" className="cancel-request" onClick={()=>controller.current?.abort()}>Cancel</button>:<button className="send" type="submit" aria-label={mode==="ask"?"Send question":"Create edit"} disabled={!picture||locked||!prompts[mode].trim()}><ArrowUp size={20}/></button>}</div>
      </form><p className="panel-footnote">{picture?"Images are sent to OpenAI only when you submit.":"A closer look. A fresh perspective."}</p>
    </aside></div>
    <Dialog open={!!inspect} onOpenChange={open=>{if(!open)setInspect(null);}}><DialogContent><DialogTitle>{inspect?.selection}</DialogTitle><DialogDescription>{inspect?.sourceVersion?`Version ${inspect.sourceVersion}`:"Original image"} · {inspect?.bounds}. Purple marks the selection used for this request.</DialogDescription>{inspect&&<img className="inspection-image" src={inspect.thumbnail} alt={`${inspect.selection} snapshot`}/>}</DialogContent></Dialog>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogTitle>A little help, a closer look.</DialogTitle><DialogDescription>Everything you need for your image workspace.</DialogDescription><div className="help-content"><h3>Connect AI</h3><p>{status?.configured?"Your server has an API key configured.":"Add OPENAI_API_KEY to the server’s .env file, then restart npm run dev. The key stays on the server."} Use an OpenAI API account with billing and image model access.</p><h3>Select, then ask or edit</h3><p>Drag a rectangle (R), paint with the brush (B), or use the whole image. Ctrl/Cmd + Z undoes your selection, then your latest edit. Ctrl/Cmd + Enter sends your prompt.</p><h3>Edits and image quality</h3><p>The AI mask guides the model. We also clip its result to your selection to preserve the surrounding working image. Fine edges can show seams. Leave space around an object when removing it.</p><p>Images are oriented automatically and reduced to a maximum 1536-pixel edge. Edits use a padded 1024/1536-pixel canvas, so selected details may be resampled. Downloads are PNGs at the working image dimensions.</p><h3>Your session</h3><p>Images and history stay in this browser tab’s memory. Refreshing clears them. OpenAI processes images when you submit. Download results before leaving. Up to 10 edits per session.</p><p className="model-info">Ask: {status?.askModel||"gpt-4.1-mini"} · Edit: {status?.editModel||"gpt-image-2"}</p></div></DialogContent></Dialog>
    <Dialog open={!!replaceFile} onOpenChange={open=>{if(!open){setReplaceFile(null);if(input.current)input.current.value="";}}}><DialogContent><DialogTitle>Start a new image?</DialogTitle><DialogDescription>This clears the current image’s questions and edits. Download any result you want to keep first.</DialogDescription><div className="replace-actions"><button className="button" onClick={download}><Download size={16}/> Download current</button><button className="button primary" onClick={()=>{const file=replaceFile;setReplaceFile(null);if(file)void loadFile(file);}}>Open new image</button></div></DialogContent></Dialog>
  </main>;
}
